""")))5

Revision ID: 7e6f0d503e9e
Revises: e722ceadfa21
Create Date: 2025-03-10 23:56:44.765530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e6f0d503e9e'
down_revision: Union[str, None] = 'e722ceadfa21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('queue_data', sa.JSON(), nullable=True),
    sa.Column('processing_times', sa.JSON(), nullable=True),
    sa.Column('avg_time', sa.Float(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('swap_requests', sa.JSON(), nullable=True),
    sa.Column('removed_user', sa.JSON(), nullable=True),
    sa.Column('last_processing_start', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queue_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queues')
    # ### end Alembic commands ###
